# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Additive log ratio
#'
#' This utility computes the additive log ratio transorm of a given vector. This transformation is
#' defined as: (METTI DEF)
#' @param x Vector of double in \ifelse{html}{\out{R<sup>H</sup>}}{\eqn{R^{H}}}.
#' @param pad_zero Boolean, default to FALSE.
#' @return Vector of double in \ifelse{html}{\out{R<sup>H-1</sup>}}{\eqn{R^{H-1}}} i.e. alr(x).
#' @export
alr <- function(x, pad_zero = FALSE) {
    .Call(`_SPMIX_alr`, x, pad_zero)
}

#' Inverse additive log ratio
#'
#' This utility computes the inverse additive log ratio transorm of a given vector. This transofrmation is
#' defined as: (METTI DEF)
#' @param x Vector of double in \ifelse{html}{\out{R<sup>H-1</sup>}}{\eqn{R^{H-1}}}.
#' @param padded_zero Boolean, default to FALSE.
#' @return Vector of double in \ifelse{html}{\out{R<sup>H</sup>}}{\eqn{R^{H}}} i.e.
#' \ifelse{html}{\out{alr <sup>-1</sup>(x)}}{\eqn{alr^{-1}(x)}}.
#' @export
inv_alr <- function(x, padded_zero = FALSE) {
    .Call(`_SPMIX_inv_alr`, x, padded_zero)
}

#' First try on the spatial sampler, taking input from files
#' @export
SPMIX_SamplerFromFiles <- function(burnin, niter, thin, data_file, w_file, params_file) {
    .Call(`_SPMIX_SPMIX_SamplerFromFiles`, burnin, niter, thin, data_file, w_file, params_file)
}

#' Simple test with stan/math C++ library
#'
#' Simply computes logN(1|2,3)
#' @export
stan_HelloWorld <- function() {
    invisible(.Call(`_SPMIX_stan_HelloWorld`))
}

#' Serialization testing
#' @export
fromProto_tostring <- function() {
    .Call(`_SPMIX_fromProto_tostring`)
}

#' Translation from serialization testing
#' @export
readingStates <- function(raw_vect) {
    invisible(.Call(`_SPMIX_readingStates`, raw_vect))
}

