# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Additive Log Ratio
#'
#' \loadmathjax This utility computes the additive log-ratio transform of a given vector. Given a generic vector of the simplex
#' \mjseqn{x \in S^{H}}, the transformation is defined as:
#' \mjsdeqn{ \operatorname{alr}(x)_j = \log \left( \frac{x_j}{x_H} \right) \quad \forall j=1,\dots,H-1 }
#'
#' @param x Vector of double in the simplex \mjseqn{S^H}.
#' @return Vector of double in \mjseqn{\mathbb{R}^{H-1}} i.e. \mjseqn{\operatorname{alr}(x)}.
#' @export
Alr <- function(x) {
    .Call(`_SPMIX_Alr`, x)
}

#' Inverse Additive Log Ratio
#'
#' \loadmathjax This utility computes the inverse additive log-ratio transform of a given vector. Given a generic vector
#' \mjseqn{ x \in \mathbb{R}^{H-1} }, the transformation is defined as:
#' \mjsdeqn{ \begin{eqnarray*}
#'	\operatorname{alr}^{-1}(x)_{j} &=& \textstyle\frac{\operatorname{e}^{x_j}}{\sum _{h} \operatorname{e}^{x_h}} \quad \forall j=1,\dots,H-1 \cr
#' \operatorname{alr}^{-1}(x)_H &=& 1 - \textstyle\sum _{h} \operatorname{alr}^{-1}(x)_h
#' 		 \end{eqnarray*} }
#'
#' @param x Vector of double in \mjseqn{ \mathbb{R}^{H-1} }.
#' @return Vector of double in the simplex \mjseqn{S^H} i.e. \mjseqn{\operatorname{alr}^{-1}(x)}.
#' @export
InvAlr <- function(x) {
    .Call(`_SPMIX_InvAlr`, x)
}

runSpatialSampler <- function(burnin, niter, thin, data, W, params_filename, covariates, boundary_detection, display_progress, seed) {
    .Call(`_SPMIX_runSpatialSampler`, burnin, niter, thin, data, W, params_filename, covariates, boundary_detection, display_progress, seed)
}

runSpatialRJSampler <- function(burnin, niter, thin, data, W, params_filename, covariates, options_filename, boundary_detection, display_progress, seed) {
    .Call(`_SPMIX_runSpatialRJSampler`, burnin, niter, thin, data, W, params_filename, covariates, options_filename, boundary_detection, display_progress, seed)
}

#' Import Proximity Matrix from File
#'
#' \loadmathjax This function simply reads the proximity matrix \mjseqn{G} of the Spatial Mixture Model from a \code{.csv} file.
#' This file should not have columns or row headers and it must be written in the visual form of a matrix
#' only composed by either \mjseqn{0} or \mjseqn{1}. As assumption, the diagonal of this matrix should be \mjseqn{0}.
#' @param filename A string identifying the path to a \code{.csv} file from which the matrix will be read.
#' @return The proximity matrix as a usual \code{R matrix} object.
#' @export
ReadMatrixFromCSV <- function(filename) {
    .Call(`_SPMIX_ReadMatrixFromCSV`, filename)
}

#' Import Data from File
#'
#' \loadmathjax This utility reads the input data for the sampler from a \code{.csv} file. This file needs to be provided
#' with column headers. Moreover, it should be organized in two columns for the correct parsing:
#' \itemize{
#' \item{\strong{group}, an integer (from \mjseqn{0} to \mjseqn{I-1}) describing the area to which the data belongs to;}
#' \item{\strong{data}, the actual data, which will be assigned to area indicated by the "group" column.}
#' }
#' @return A list of dimension \mjseqn{I}, in which the \mjseqn{i}-th element is a vector containing all data that
#' have been assigned to the \mjseqn{i}-th location.
#' @export
ReadDataFromCSV <- function(filename) {
    .Call(`_SPMIX_ReadDataFromCSV`, filename)
}

#' Compute the log posterior densities for each group and for each data point
#'
#' \loadmathjax This utility takes as input the deserialized output of the samplers
#' (via \code{\link{DeserializeSPMIXProto}}) and compute the chain of posterior log-likelihood
#' for each data point
#'
#' @param serialized_states A list of `raw` vectore which stores the serialized output of
#' the sampler (either with a fixed or a variable number of components).
#' @param data The data that needs to be fitted by the model. Data are passed as a list of vectors, whose
#' \mjseqn{i}-th element represents the vector of data assigned to the \mjseqn{i}-th location.
#' @param display_progress A bool. If \code{TRUE}, prints the progress of the computation.
#' 
#' @return A \mjseqn{T \times N} matrix, \mjseqn{T} being the number of iterations
#' of the MCMC chain and \mjseqn{N} the total number of data points.
#' Element \mjseqn{t,n} of the matrix is the log-likelihood of the \mjseqn{n}-th
#' data point at \mjseqn{t}-th iteration.
#'
#' @export
ComputePosteriorLPDFs <- function(serialized_states, data, display_progress = TRUE) {
    .Call(`_SPMIX_ComputePosteriorLPDFs`, serialized_states, data, display_progress)
}

#' Compute the log predictive densities for each group across a grid of values.
#'
#' Given the serialized MCMC chain from \code{Sampler.DensityEstimation} or \code{Sampler.BoundaryDetection}, this function
#' computes the predictive log density in each area over the points specified by \code{grid}.
#'
#' @param serialized_states A list of `raw` vectors, where each element is a serialized `UnivariateState` protobuf object.
#' Each serialized state represents a sample from the MCMC chain.
#' @param grid An numeric vector representing the grid of values at which to compute the predictive log pdf.
#' @param display_progress (Optional) a bool, if `TRUE`, it display a progress bar during the computation.
#'
#' @return A list of matrices. Each element of the list is associated to a group and contains a matrix of size
#' `number_of_iterations` times `len(grid)`, each element representing the log predictive density for that group
#' at the corresponding iteration and grid point.
#'
#' @export
ComputePredictiveLPDFs <- function(serialized_states, grid, display_progress = TRUE) {
    .Call(`_SPMIX_ComputePredictiveLPDFs`, serialized_states, grid, display_progress)
}

