# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Additive Log Ratio
#'
#' This utility computes the additive log ratio transorm of a given vector. This transformation is
#' defined as: (METTI DEF)
#' @param x Vector of double in \ifelse{html}{\out{R<sup>H</sup>}}{\eqn{R^{H}}}.
#' @return Vector of double in \ifelse{html}{\out{R<sup>H-1</sup>}}{\eqn{R^{H-1}}} i.e. alr(x).
#' @export
alr <- function(x) {
    .Call(`_SPMIX_alr`, x)
}

#' Inverse Additive Log Ratio
#'
#' This utility computes the inverse additive log ratio transorm of a given vector. This transformation is
#' defined as: (METTI DEF)
#' @param x Vector of double in \ifelse{html}{\out{R<sup>H-1</sup>}}{\eqn{R^{H-1}}}.
#' @return Vector of double in \ifelse{html}{\out{R<sup>H</sup>}}{\eqn{R^{H}}} i.e.
#' \ifelse{html}{\out{alr <sup>-1</sup>(x)}}{\eqn{alr^{-1}(x)}}.
#' @export
invAlr <- function(x) {
    .Call(`_SPMIX_invAlr`, x)
}

runSpatialSampler <- function(burnin, niter, thin, data, W, params, covariates, display_progress) {
    .Call(`_SPMIX_runSpatialSampler`, burnin, niter, thin, data, W, params, covariates, display_progress)
}

runSpatialRJSampler <- function(burnin, niter, thin, data, W, params, covariates, options, display_progress) {
    .Call(`_SPMIX_runSpatialRJSampler`, burnin, niter, thin, data, W, params, covariates, options, display_progress)
}

#' Import Proximity Matrix from File
#'
#' This function simply reads the proximity matrix G of the Spatial Mixture Model from a \code{.csv} file. This file
#' needs to be provided with no columns or row headers and in the visual form of a matrix only composed by 0 or 1.
#' As assumption, the diagonal of this matrix should be 0.
#' @param filename A string identifying the path to a \code{.csv} file from which the matrix will be read.
#' @return The proximity matrix as a usual \code{R matrix} object.
#' @export
readMatrixFromCSV <- function(filename) {
    .Call(`_SPMIX_readMatrixFromCSV`, filename)
}

#' Import Data from File
#'
#' This utility reads the input data for the sampler from a \code{.csv} file. This file needs to be provided with column headers.
#' The file should be organized in two columns for a correct read:
#' \itemize{
#' \item{\strong{group}, an integer (from 0 to I-1) describing the area to which the datum belongs to;}
#' \item{\strong{data}, the actual datum, which will be assigned to area indicated by "group" column.}
#' }
#' @return A list of dimension I, in which the i-th element is a vector containing all data that have been assigned to location i.
#' @export
readDataFromCSV <- function(filename) {
    .Call(`_SPMIX_readDataFromCSV`, filename)
}

